const userQuery = require(__basedir+"/query/code_query");
const nodemailer = require("nodemailer");
const request = require('request');
exports.post = async function (req,res){
  console.log(req.body.email);
  // console.log(req.params['email']);
  //Routine for sending the password reset email to the registered user that requested it.
  //We are generating a link by getting a general firebase link that leads to the password change screen in the app
  //while also appending the users id and password request id in order to see if the user still exists by the time they reach that screen
  //and if the link is still valid/was ever valid by the time the user clicks on it.
  //we are just using the unique id generated by mongodb in order to get the password request id
  try{
    let user = await userQuery.find(
      {
      email: req.body.email
    });
    console.log(user);
    if (user) {
      let code= nanoid(10);
      console.log(code);
      let newCode = new Code;
      newCode.code = code;
      newCode.id = user.id;
    let saveCode = await newCode.save();
        const userEmail = `${req.body.email}`;
          const output = `<p>This email was sent to you because a password reset was requested on your account.</p>
          <p> Here is your code: ${code}</a></p>
          <p>Please follow the following instructions carefully, as this code will expire in 5 minutes. Do not share this code with anyone.</p>
          <p> - Open Your Juice Fit Life App </p>
          <p> - On the log-in screen, click on 'Forgot your password? Click here!'</p>
          <p> - Click on 'Already have a pin?'</p>
          <p> - Type in the code that was emailed to you into the field that says 'Your Code' and click the 'Check Code' Button</p>
          <p> You should be able to then create a new password. Please take care to remember your password this time!</p>
          <p>If you did not request a password change then please disregard this email. Only those who have access to your email can use that code to change your password.</p>
          <p> - The Juice Fit Life Team </p>
          <p>Do not reply to this email. This email has been automatically generated.</p>`;

            // send mail with defined transport object
            let transporter = transport.transportcreation();
            transporter.sendMail({
              from: `Juice Fit Life <${process.env.EMAIL}>`, // sender address
              to: `${userEmail}`, // list of receivers
              subject: "You have requested a password reset", // Subject line
              text: "Password Reset", // plain text body
              html: output, // html body
            });
            res.send(true);
  }
  else{
    res.send(true);
  }
}
  catch(e){
    console.log(e);
    res.sendStatus(500);
  }
}
